version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "127.0.0.1:7000:80"
    restart: always
    env_file:
      .env

  api:
    build:
      context: ./api
    ports:
      - "127.0.0.1:9000:80"
    restart: always
    env_file:
      .env

volumes:
  db-data:
  geoserver-data:
  upload-data:
