version: "3.8"
services:
  cm-multiply:
    build:
      context: ./cm
      dockerfile: example_multiply/Dockerfile
    environment:
      UPLOAD_DIR: /upload-dir
    volumes:
      - upload-data:/upload-dir
    env_file:
      .env

  cm-empty:
    build:
      context: ./cm
      dockerfile: example_empty/Dockerfile
    environment:
      UPLOAD_DIR: /upload-dir
    volumes:
      - upload-data:/upload-dir
    env_file:
      .env

  frontend:
    build:
      context: ./frontend
    ports:
      - "127.0.0.1:7000:80"
    restart: always
    depends_on:
      - "api"
    env_file:
      .env

  api:
    build:
      context: ./api
    ports:
      - "127.0.0.1:9000:80"
    restart: always
    environment:
      UPLOAD_DIR: /upload-dir
      RASTER_DB_DIR: /raster-db-dir
    volumes:
      - upload-data:/upload-dir
      - data:/raster-db-dir
    env_file:
      .env


  postgrest:
    build:
      context: ./postgrest
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
      - .postgrest

  redis:
    image: redis:6-alpine
    ports:
      - "127.0.0.1:6379:6379"
  flower:
    image: mher/flower:0.9.4
    ports:
      - "127.0.0.1:5555:5555"
    env_file:
      .env

volumes:
  upload-data:
  data:
  web:
