version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "127.0.0.1:7000:80"
    restart: always
    env_file:
      .env

  api:
    build:
      context: ./api
    ports:
      - "127.0.0.1:9000:80"
    restart: always
    environment:
      UPLOAD_DIR: /upload-dir
    volumes:
      - upload-data:/upload-dir
    env_file:
      .env

  db:
    build:
      context: ./db
    ports:
      - "127.0.0.1:5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    stop_signal: SIGINT                 # Fast Shutdown mode
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      .env

volumes:
  upload-data:
  db-data:
