name: Integration test after PR reviewed

on:
  pull_request_review:
    types: [submitted]

jobs:
  test:
    if: github.event.review.state == 'approved'
    runs-on: 'ubuntu-18.04'

    steps:
      - uses: actions/checkout@v2
      - name: start the stack
        run: docker-compose up -d --build
      - name: run integration test
        run: docker-compose exec -T api ./test.py integration
