# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: 'ubuntu-18.04'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - run: |
          # Hack to get setup-python to work on act
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: install linters
        run: pip install -r api/linter-requirements.txt

      - name: check-lint with black
        run: black --check api
      - name: check-lint with bandit
        run: cd api && bandit -r .
      - name: check-lint with isort
        run: cd api && isort --check --diff .

      - name: Run docker-compose stack
        run: docker-compose build --parallel
